config/routes.rb
Intech::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  post 'basket' => 'basket#add', :as => :basket_add
  delete 'basket/:item' => 'basket#remove', :as => :basket_remove
  get 'basket' => 'basket#show', :as => :basket

  resources :series, :only => [:index, :show] do
    resources :events, :only => [:show]
  end

  root :to => 'series#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :series
  delegate :title, :to => :series, :prefix => true, :allow_nil => true
  has_many :lectures

  validates_presence_of :title, :series_id, :time

  scope :active, lambda { where(:open => true).where('events.time > ?', Time.now) }

  def date
    time.to_date
  end

  def active_lectures
    lectures.active
  end

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base

  belongs_to :event
  #delegate :title, :to => :series, :prefix => true, :allow_nil => true

  validates_presence_of :title, :event_id, :time

  scope :active, lambda { where(:open => true).where('lectures.time > ?', Time.now) }

  def date
    time.to_date
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :lines, :class_name => 'OrderLine'

  def add(data)
    line = find_item_line(data[:item_id].to_i)
    if line.nil?
      lines.build(data)
      save
    else
      line.quantity += data[:quantity].to_i
      line.save
    end
  end

  def remove(item)
    line = find_item_line(item)
    if line
      lines.delete(line)
      save
    end
  end

  def find_item_line(item)
    item = item.id unless item.is_a? Fixnum
    lines.all.find {|line| line.item_id == item}
  end

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base

  belongs_to :order
  belongs_to :item, :class_name => 'Event'

  delegate :title, :to => :item
end

app/models/series.rb
class Series < ActiveRecord::Base

  has_many :events

  validates_presence_of :title

  scope :active, where(:active => true)

  def active_events
    events.active
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_basket

  after_filter :save_basket_id

  def current_basket
    return @current_basket unless @current_basket.nil?
    @current_basket = Order.find_by_id(session[:basket_id]) unless session[:basket_id].nil?
    @current_basket = Order.new if @current_basket.nil?
    return @current_basket
  end

  private
  def save_basket_id
    session[:basket_id] = current_basket.id
  end

end

app/controllers/basket_controller.rb
class BasketController < ApplicationController

  def add
    current_basket.add(params[:order_line])
    redirect_to basket_path
  end

  def show
  end

  def remove
    current_basket.remove(Event.find(params[:item]))
    redirect_to basket_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    series = Series.active.find(params[:series_id])
    @event = series.active_events.find(params[:id])
    @event_item = OrderLine.new(:item => @event, :quantity => 1)
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  def index
    @series = Series.active
  end

  def show
    @series = Series.active.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/lectures/_lecture.html.haml
.lecture
  %h3= link_to lecture.title, [:edit, :admin, @series, lecture]
  %p= lecture.time.pretty
  %p
    Series:
    = lecture.series_title

app/views/admin/lectures/edit.html.haml
= simple_form_for [:admin, @series, @lecture] do |f|
  = f.input :title
  %fieldset
    %legend Time
    = f.input :time
  = f.input :open
  = f.association :series
  = f.input :details
  = f.submit

app/views/admin/lectures/index.html.haml
%h1
  = @series ? @series.title : 'All'
  Lectures

= render @lectures

= link_to 'Add new Lecture', [:new, :admin, @series, :lecture]

app/views/admin/series/_series.html.haml
.series
  %p
    %b= link_to series.title, admin_series_lectures_path(series)
    = link_to 'edit', edit_admin_series_path(series)

app/views/admin/series/edit.html.haml
= simple_form_for [:admin, @series] do |f|
  = f.input :title
  = f.input :active
  = f.input :details
  = f.submit

app/views/admin/series/index.html.haml
%h1 Series

= render @series

= link_to 'Add new Series', new_admin_series_path

app/views/admin/series/show.html.haml
%h2= @series.title

=render @series.lectures

app/views/basket/show.html.haml
%h2 Basket

%table.basket
  - current_basket.lines.each do |line|
    %tr
      %td= line.title
      %td= line.quantity
      %td= line.price
      %td= button_to 'Remove', basket_remove_path(:item => line.item), :method => :delete

app/views/events/show.html.haml
%h2= @event.title
.date= @event.date.pretty
.details= @event.details
- @event.active_lectures.each do |lecture|
  = lecture.title
  = lecture.details
= form_for @event_item, :url => basket_add_path do |f|
  = f.hidden_field :item_id
  = f.text_field :quantity
  = f.submit 'Add to basket'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Intech
    = stylesheet_link_tag 'layout'
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body{:class => @section}

    .container
      = flash[:notice]
      = yield

app/views/series/index.html.haml
%h1 Series

%ul
  - @series.each do |series|
    %li= link_to series.title, series

app/views/series/show.html.haml
%h2= @series.title
.details= @series.details

%ul
  - @series.active_events.each do |event|
    %li= link_to event.title, [@series, event]